apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rsoaresd-tenant/devfile-sample/devfile-sample@sha256:2c1dcff88c9caa9d8c0d5d2592abb432cfb9f54173bec4973d69a6088e68ddf1
        name: my-nodejs
        resources: {}
status: {}
